### ISSUE TITLE
有没有点击按钮触发下拉刷新的方法，或者添加一个这种方法

### ISSUE THREAD

**Issue by SaraLee12** [reactjs-ui/reactjs-iscroll#6]
如题

**Comment by hopefuture** [comment]
该组件已废弃，请使用组件 [reactjs-pull-refresh](https://github.com/reactjs-ui/reactjs-pull-refresh) 来代替

**Comment by hopefuture** [comment]
该组件已废弃，请使用组件 [reactjs-pull-refresh](https://github.com/reactjs-ui/reactjs-pull-refresh)  或 [react-alloytouch](https://github.com/reactjs-ui/react-alloytouch) 来代替
